version: '3.6'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dummy_test
