development: &default
  adapter: postgresql
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: dummy_development
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: dummy_test
